//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PairPark.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class refresh_tokens
    {
        public string id { get; set; }
        public string driver_nickname { get; set; }
        public string client_id { get; set; }
        public System.DateTime issued_utc { get; set; }
        public System.DateTime expires_utc { get; set; }
        public string protected_ticket { get; set; }
        public int driver_id { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual drivers drivers { get; set; }
    }
}
